// 通过选项创建 VueI18n 实例
	let i18n = new VueI18n({
	    locale: localStorage.getItem('locale') || 'zh-cn', // 设置地区
	    messages: {
		    en: {
				header: {
				  home: 'HOME',
				  buy: 'BUY',
				  sale: 'SALE',
				  bargain: 'CAR OUTLET',
				  hire: 'LOAN',
				  about: 'ABOUT',
				  center: 'PERSONAL CENTER',
						top: 'top',
						online: 'consult<br>ation',
				},
				search: {
					place: "What's in your mind?"
				},
				price: [{id:1, detail:'Under $10000'},{id:2, detail:'$10000-$15000'},{id:3, detail:'$15000-$20000'},{id:4,detail:'$20000-$30000'},{id:5,detail:'$30000-$40000'},{id:6,detail:'$40000 Over'}],
				cartype:[{'logo':'make0.png','name':'Audi'},
				{'logo':'make1.png','name':'BMW'},
				{'logo':'make2.png','name':'Ford'},
				{'logo':'make3.png','name':'Honda'},
				{'logo':'make4.png','name':'Mercedes-Benz'}],
				more: 'More',
				recom: 'CHAMPION Recommoned',
				seltype: ['Latest-hot','ECO-Car','Prospective-new-car','luxury-car'],
				explain: [],
				mediaVoice: 'Media voice',
				media: [],
				misc: [{"content":'Service agreement','src':"serivceAgreement.html"},
				{"content":'Privacy statement','src':"private.html"},
				{"content":'Suggestion feedback','src':"feedback.html"},
				{"content":'Contact us','src':"contactUs.html"}],
				tipsArr:['Free transfer','A variety of financial loan services','Within a year the national road rescue service','Multiple payment channels (POS machine, WeChat, alipay, etc.)','There is no 100% commission'],
				wantBuy: 'Search',
				hotSearch: 'Hot Search',
				hotsearchArr: [],
				comment: [],
				adv1: 'CHAMPION is dedicated to delivering a premium car experience',
				storyTitle: 'CHAMPION Story',
				storyDes: 'Buy Car description',
				froms: 'from ',
				scom: "'s comment",
				strongRecom: 'is highly recommended',
				score: 'score',
				address: 'Massachusetts state',
			},
		    'zh-cn': {
				header: {
					home: '首页',
					buy: '我要买车',
					sale: '我要卖车',
					bargain: '车行值购',
					hire: '分期购车',
					about: '关于车行',
					center: '个人中心',
					top: '返回<br>顶部',
					online: '在线<br>咨询',
				},
					search: {
						place: "此处搜索车型！！！"
					},
					price: [{id:1,detail:'$1万以下'},{id:2,detail:'$1万-$1.5万'},{id:3,detail:'$1.5万-$2万'},{id:4,detail:'$2万-$3万'},{id:5,detail:'$3万-$4万'},{id:6,detail:'$4万以上'}],
					cartype: [{'logo':'make0.png','name':'奥迪'},
					{'logo':'make1.png','name':'宝马'},
					{'logo':'make2.png','name':'福特'},
					{'logo':'make3.png','name':'本田'},
					{'logo':'make4.png','name':'奔驰'}],
					more: '更多',
					recom: '车行推荐',
					seltype: ['最新最热','经济实惠','准新车','豪华车'],
					explain: [],
					mediaVoice: '媒体声音',
					media: [],
					misc: [{"content":'服务协议','src':"serivceAgreement.html"},
					{"content":'隐私声明','src':"private.html"},
					{"content":'意见反馈','src':"feedback.html"},
					{"content":'联系我们','src':"contactUs.html"}],
					tipsArr:['免费代办过户','多种金融贷款服务','一年内全美道路救援服务','多种支付渠道（POS机、微信、支付宝等）多种支付渠道（POS机、微信、支付宝等）','100%无佣金'],
					wantBuy: '我要买车',
					hotSearch: '热门搜索',
					hotsearchArr: [],
					comment: [],
					adv1: 'CHAMPION 专为用户带来更加优质的购车体验',
					storyTitle: 'CHAMPION 故事',
					storyDes: '购车描述',
					froms: '来自',
					scom: '的评价',
					strongRecom: '强烈推荐',
					score: '分',
					address: '马塞诸萨州',
			}
		}// 设置地区信息
	})